import type { OsStore } from "./types";

export function createSeedStore(): OsStore {
  return {
    version: 1,
    updated_at: new Date().toISOString(),
    leads: [
      {
        id: "LEAD-2026-000145",
        lead_id: "LEAD-2026-000145",
        business_name: "Hartley Estate Agents",
        contact: "Marcus Hartley",
        phone: "+447700900123",
        email: "marcus@hartley.co.uk",
        website: "hartleyestates.co.uk",
        industry: "Real Estate",
        location: "Manchester, UK",
        source: "Scraped Data",
        product_interest: "Dubai Real Estate CRM",
        estimated_value: 8500,
        lead_score: 72,
        status: "New",
        setter_stage: "New",
        closer_stage: null,
        assigned_to: "u3",
        closer_id: null,
        affiliate_id: null,
        last_contact: null,
        next_followup: "2026-06-13",
        notes: "",
        activities: [],
        created_at: "2026-06-10",
      },
      {
        id: "LEAD-2026-000146",
        lead_id: "LEAD-2026-000146",
        business_name: "Peak Pilates Studio",
        contact: "Sarah Chen",
        phone: "+447911234567",
        email: "sarah@peakpilates.com",
        website: "peakpilates.com",
        industry: "Pilates & Fitness",
        location: "London, UK",
        source: "Affiliate",
        product_interest: "Pilates Studio Software",
        estimated_value: 4200,
        lead_score: 81,
        status: "Interested",
        setter_stage: "Appointment Booked",
        closer_stage: "Qualified",
        assigned_to: "u3",
        closer_id: "u5",
        affiliate_id: "aff1",
        last_contact: "2026-06-12",
        next_followup: "2026-06-14",
        notes: "Affiliate referral — high intent",
        activities: [
          {
            id: "a1",
            type: "call",
            text: "Intro call — 12 mins",
            user: "Sarah Ahmed",
            at: "2026-06-12T10:00:00Z",
          },
        ],
        created_at: "2026-06-08",
      },
      {
        id: "LEAD-2026-000147",
        lead_id: "LEAD-2026-000147",
        business_name: "Gulf Realty Group",
        contact: "Aisha Al Mansoori",
        phone: "+971501234567",
        email: "aisha@gulfrealty.ae",
        website: "gulfrealty.ae",
        industry: "Real Estate",
        location: "Dubai, UAE",
        source: "Marketing",
        product_interest: "Dubai Real Estate CRM",
        estimated_value: 12000,
        lead_score: 88,
        status: "Negotiation",
        setter_stage: "Passed To Closer",
        closer_stage: "Negotiation",
        assigned_to: "u4",
        closer_id: "u5",
        affiliate_id: null,
        last_contact: "2026-06-11",
        next_followup: "2026-06-13",
        notes: "Proposal sent £499/mo + setup",
        activities: [],
        created_at: "2026-05-28",
      },
    ],
    clients: [
      {
        id: "CL-2026-000487",
        client_id: "CL-2026-000487",
        lead_id: "LEAD-2026-000147",
        business_name: "Alpha Broker LLC",
        contact_name: "Omar Al Farsi",
        email: "omar@alphabroker.ae",
        phone: "+971501112233",
        industry: "Real Estate",
        product: "Dubai Real Estate CRM",
        stage: "Onboarding",
        monthly_price: 499,
        setup_fee: 3500,
        contract_value: 9488,
        lifetime_revenue: 9488,
        renewal_date: "2027-06-01",
        affiliate_id: "aff1",
        setter_id: "u3",
        closer_id: "u5",
        portal_sync: "Synced",
        portal_enabled: true,
        build_progress: 45,
        deposit_paid: true,
        assigned_to: "u1",
        created_at: "2026-06-01",
      },
      {
        id: "client-whitfield",
        client_id: "client-whitfield",
        lead_id: null,
        business_name: "Whitfield Group",
        contact_name: "Sarah Whitfield",
        email: "demo@nexdesk.app",
        phone: "+447700900999",
        industry: "Real Estate",
        product: "Real Estate CRM Platform",
        stage: "Onboarding",
        monthly_price: 499,
        setup_fee: 8500,
        contract_value: 14488,
        lifetime_revenue: 14488,
        renewal_date: "2027-04-01",
        affiliate_id: null,
        setter_id: "u2",
        closer_id: "u5",
        portal_sync: "Synced",
        portal_enabled: true,
        build_progress: 72,
        deposit_paid: true,
        assigned_to: "u2",
        created_at: "2026-04-01",
      },
    ],
    projects: [
      {
        id: "proj-alpha-crm",
        client_id: "CL-2026-000487",
        name: "Dubai Real Estate CRM",
        category: "Off-the-Shelf Systems",
        status: "In Progress",
        progress: 45,
        current_stage: "Development",
        estimated_completion: "30 Jul 2026",
        latest_update: "Pipeline and property modules configured for Alpha Broker.",
        updates: [
          {
            id: "u-alpha-1",
            date: "16 Jun 2026",
            author: "NexDesk Team",
            message: "User roles and permissions configured.",
          },
        ],
      },
      {
        id: "proj-website",
        client_id: "client-whitfield",
        name: "Corporate Website",
        category: "Websites",
        status: "In Progress",
        progress: 72,
        current_stage: "Development",
        estimated_completion: "15 Jul 2026",
        latest_update: "Homepage and services pages deployed to staging for review.",
        updates: [
          {
            id: "u1",
            date: "16 Jun 2026",
            author: "NexDesk Team",
            message: "Phase 2 staging build approved internally.",
          },
        ],
      },
      {
        id: "proj-crm",
        client_id: "client-whitfield",
        name: "Real Estate CRM Platform",
        category: "Bespoke Systems",
        status: "In Progress",
        progress: 58,
        current_stage: "Internal Testing",
        estimated_completion: "1 Aug 2026",
        latest_update: "Staging environment live — awaiting UAT feedback.",
        updates: [
          {
            id: "u2",
            date: "14 Jun 2026",
            author: "NexDesk Team",
            message: "CRM staging environment provisioned.",
          },
        ],
      },
    ],
    subscriptions: [
      {
        id: "sub1",
        client_id: "CL-2026-000487",
        client_name: "Alpha Broker LLC",
        product: "Dubai Real Estate CRM",
        status: "Active",
        mrr: 499,
        started: "2026-06-01",
        renewal: "2027-06-01",
      },
      {
        id: "sub-whitfield-crm",
        client_id: "client-whitfield",
        client_name: "Whitfield Group",
        product: "Real Estate CRM Platform",
        status: "Active",
        mrr: 499,
        started: "2026-04-01",
        renewal: "2027-04-01",
      },
    ],
    invoices: [
      {
        id: "INV-2026-00421",
        client_id: "CL-2026-000487",
        client_name: "Alpha Broker LLC",
        amount: 3500,
        status: "Paid",
        due_date: "2026-06-05",
        paid_at: "2026-06-04",
        products: ["Setup Fee — Dubai CRM"],
      },
      {
        id: "INV-2026-00422",
        client_id: "CL-2026-000487",
        client_name: "Alpha Broker LLC",
        amount: 499,
        status: "Paid",
        due_date: "2026-06-01",
        paid_at: "2026-06-01",
        products: ["Monthly Subscription"],
      },
      {
        id: "inv-1042",
        client_id: "client-whitfield",
        client_name: "Whitfield Group",
        amount: 18500,
        status: "Due",
        due_date: "2026-06-25",
        paid_at: null,
        products: ["CRM Build Milestone 2"],
      },
    ],
    support: [
      {
        id: "t1",
        client_id: "CL-2026-000487",
        client_name: "Alpha Broker LLC",
        subject: "Portal login issue",
        status: "In Progress",
        priority: "high",
        satisfaction: null,
        created_at: "2026-06-11",
      },
    ],
    portal_users: [
      {
        client_id: "CL-2026-000487",
        email: "omar@alphabroker.ae",
        password: "AlphaBroker2026!",
        name: "Omar Al Farsi",
        company: "Alpha Broker LLC",
      },
      {
        client_id: "client-whitfield",
        email: "demo@nexdesk.app",
        password: "NexDesk2026!",
        name: "Sarah Whitfield",
        company: "Whitfield Group",
      },
    ],
  };
}
